language: objective-c
osx_image: xcode16
before_install:
- gem install cocoapods
script:
- set -o pipefail && xcodebuild test -workspace Example/MKUnits.xcworkspace -scheme MKUnits-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
