

pod 'MKFoundationKit/NSNumber'

target :MKUnitsTests, :exclusive => true do
    pod 'OCHamcrest',	'>= 3.0.0'
#	pod 'OCMock',     	'>= 2.1.1'
#	pod 'Kiwi',		 	'>= 2.1.0'
#	pod 'Specta',		'>= 0.1.8'
end

